// todo/src/components/Todo.tsx
import { useState } from "react";
import TodoEditor from "./TodoEditor";
import TodoHeader from "./TodoHeader";
import TodoList from "./TodoList";

export default function Todo() {
  const [todolist, setTodolist] = useState<string[]>([]);
  return (
    <div className="max-w-md mx-auto shadow-lg rounded-lg overflow-hidden">
      <TodoHeader />
      <TodoEditor todolist={todolist} setTodolist={setTodolist} />
      <TodoList todolist={todolist} setTodolist={setTodolist} />
    </div>
  );
}

// 20250110/todoPinia/src/components/Todo.vue
<script setup>
import { ref } from "vue";
import TodoEditor from "./TodoEditor.vue";
import TodoHeader from "./TodoHeader.vue";
import TodoList from "./TodoList.vue";
</script>
<template>
  <div className="max-w-md mx-auto shadow-lg rounded-lg overflow-hidden">
    <TodoHeader />
    <TodoEditor />
    <TodoList />
  </div>
</template>
<style></style>
