// todo/pinia/src/components/Todo.vue
<script>
import TodoEditor from "./TodoEditor.vue";
import TodoHeader from "./TodoHeader.vue";
import TodoList from "./TodoList.vue";
import { useTodoStore } from "../stores/todoStore";

export default {
  components: {
    TodoHeader,
    TodoEditor,
    TodoList,
  },
  setup(){
    const todoStore = useTodoStore();
    return {todoStore};
  },
};
</script>
<template>
  <div className="max-w-md mx-auto shadow-lg rounded-lg overflow-hidden">
    <TodoHeader />
    <TodoEditor @add-todo="todoStore.addTodo"/>
    <TodoList
      :todos="todoStore.todos"
      @delete-todo="todoStore.deleteTodo"
      @toggle-todo="todoStore.toggleTodo"
    />
  </div>
</template>
<style></style>

// 20241202/todoReducer/src/components/Todo.tsx
import { useReducer } from "react";
import TodoEditor from "./TodoEditor";
import TodoHeader from "./TodoHeader";
import TodoList from "./TodoList";
import { todosReducer } from "./reducer/reducer";

export default function Todo() {
  const [todos, todosDispatch] = useReducer(todosReducer, []);

  const handleAddTodo = (newTodo: string) =>
    todosDispatch({ type: "ADD", payload: newTodo });
  const handleDeleteTodo = (deleteTodo: string) =>
    todosDispatch({ type: "DELETE", payload: deleteTodo });

  return (
    <div className="max-w-md mx-auto shadow-lg rounded-lg overflow-hidden">
      <TodoHeader />
      <TodoEditor handleAdd={handleAddTodo} />
      <TodoList todos={todos} handleDelete={handleDeleteTodo} />
    </div>
  );
}
