// TodoList-pinia/src/components/TodoList.vue
<script setup>
import TodoListItem from "./TodoListItem.vue"
import { useTodoStore } from '@/stores/todoStore';

const store = useTodoStore()
</script>

<template>
  <ul className="divide-y divide-gray-200">
    <TodoListItem
      v-for="todo in store.todos"
      :key="todo.id"
      :todo="todo"
    />
  </ul>
</template>

// 20241202/todoReducer/src/components/TodoList.tsx
import TodoListItem from "./TodoListItem";

export default function TodoList({ todos, handleDelete }: TodoListProps) {
  return (
    <ul className="divide-y divide-gray-200">
      {todos.map((todo, index) => (
        <TodoListItem key={index} todo={todo} handleDelete={handleDelete} />
      ))}
    </ul>
  );
}
