// 20241203/todo_useEffect/src/components/TodoList.tsx
import TodoListItem from "./TodoListItem";

export default function TodoList({
  todos,
  toggleTodo,
  removeTodo,
}: {
  todos: Todo[];
  toggleTodo: (id: number) => void;
  removeTodo: (id: number) => void;
}) {
  return (
    <ul className="divide-y divide-gray-200">
      {todos.length > 0 &&
        todos.map((todo) => (
          <TodoListItem
            key={todo.id}
            todo={todo}
            toggleTodo={toggleTodo}
            removeTodo={removeTodo}
          />
        ))}
    </ul>
  );
}

// 20250110/todo/src/components/TodoList.vue
<script setup>
import TodoListItem from "./TodoListItem.vue";

const props = defineProps({
  todos: Array,
  toggleTodo: Function,
  removeTodo: Function,
});
</script>
<template>
  <ul className="divide-y divide-gray-200">
    <TodoListItem
      v-for="(item, index) in todos"
      :key="index"
      :item
      :toggleTodo
      :removeTodo
    />
  </ul>
</template>
<style></style>
