// 20241202/todo/src/components/TodoListItem.tsx
interface Todo {
  id: number;
  text: string;
  done: boolean;
}

interface Props {
  todo: Todo;
  onFinish: () => void;
  onDelete: () => void;
}

export default function TodoListItem({ todo, onFinish, onDelete }: Props) {
  return (
    <li className="flex items-center justify-between p-3 transition-colors border-b hover:bg-gray-100">
      <div className="flex items-center">
        <input
          type="checkbox"
          checked={todo.done}
          onChange={onFinish}
          className="w-4 h-4 mr-3 text-blue-500 focus:ring-blue-400"
        />
        <span className={todo.done ? "line-through text-gray-500" : ""}>
          {todo.text}
        </span>
      </div>
      <button
        onClick={onDelete}
        className="ml-4 text-red-500 hover:text-red-700"
      >
        Delete
      </button>
    </li>
  );
}

// 20250113/vue3_todo/src/components/TodoListItem.vue
<script setup>
const props = defineProps({
  todo: {
    type: Object,
  },
});
const emits = defineEmits(["toggle-todo", "delete-todo"]);
</script>
<template>
  <li
    class="flex items-center justify-between p-3 border-b hover:bg-gray-100 transition-colors"
  >
    <div :class="`flex items-center ${props.todo.done && 'line-through'}`">
      <input
        type="checkbox"
        class="mr-3 h-4 w-4 text-blue-500 focus:ring-blue-400"
        :checked="props.todo.done"
        @change="emits('toggle-todo', props.todo.id)"
      />
      <span>{{ props.todo.text }}</span>
    </div>
    <button
      class="text-red-500 hover:text-red-700 ml-4"
      @click="emits('delete-todo', props.todo.id)"
    >
      Delete
    </button>
  </li>
</template>
<style></style>
