// 20241202_01/todo/src/components/TodoList.tsx
import TodoListItem from "./TodoListItem";
import { TodoItem } from "./Todo";

interface TodoListProps {
  todos: TodoItem[];
  toggleTodo: (id: string) => void;
  deleteTodo: (id: string) => void;
}

export default function TodoList({
  todos,
  toggleTodo,
  deleteTodo,
}: TodoListProps) {
  return (
    <ul className="divide-y divide-gray-200">
      {todos.map((todo) => (
        <TodoListItem
          key={todo.id}
          todo={todo}
          toggleTodo={toggleTodo}
          deleteTodo={deleteTodo}
        />
      ))}
    </ul>
  );
}

// 20250113/vue3_todo/src/components/TodoList.vue
<script setup>
import TodoListItem from "./TodoListItem.vue";
const props = defineProps({
  todos: {
    type: Array,
    default() {
      return [];
    },
  },
});
const emits = defineEmits(["toggle-todo", "delete-todo"]);
const toggleTodo = (id) => {
  emits("toggle-todo", id);
};
const deleteTodo = (id) => {
  emits("delete-todo", id);
};
</script>
<template>
  <ul class="divide-y divide-gray-200">
    <TodoListItem
      v-for="todo in props.todos"
      :key="todo.id"
      :todo="todo"
      @toggle-todo="toggleTodo"
      @delete-todo="deleteTodo"
    />
  </ul>
</template>
<style></style>
