// 20241202/task/src/components/TodoList.tsx
import TodoListItem from "./TodoListItem";

export default function TodoList({
  todos,
  onToggle,
  onDelete,
}: {
  todos: { text: string; completed: boolean }[];
  onToggle: (index: number) => void;
  onDelete: (index: number) => void;
}) {
  return (
    <ul className="divide-y divide-gray-200">
      {todos.map((todo, index) => (
        <TodoListItem
          key={index}
          todo={todo}
          onToggle={() => onToggle(index)}
          onDelete={() => onDelete(index)}
        />
      ))}
    </ul>
  );
}

// 20250110/pinia-method/src/components/TodoList.vue
<script setup>
import { useTodoStore } from "@/store/todoStore";
import TodoListItem from "./TodoListItem.vue";

const todoStore = useTodoStore();
const { todos } = todoStore;
</script>
<template>
  <ul
    className="divide-y divide-gray-200"
    v-for="(todo, index) in todos"
    :key="index"
  >
    <TodoListItem
      :title="todo.text"
      :completed="todo.completed"
      :currentIndex="index"
    />
  </ul>
</template>
<style></style>
