// 20250110-2/src/components/Todo.vue
<script setup>
import TodoEditor from "./TodoEditor.vue";
import TodoHeader from "./TodoHeader.vue";
import TodoList from "./TodoList.vue";



</script>
<template>
  <div className="max-w-md mx-auto shadow-lg rounded-lg overflow-hidden">
    <TodoHeader />
    <TodoEditor />
    <TodoList />
  </div>
</template>
<style></style>

// 20241202/todo/src/components/Todo.tsx
import { useState } from "react";
import TodoEditor from "./TodoEditor";
import TodoHeader from "./TodoHeader";
import TodoList from "./TodoList";

export default function Todo() {
  const [items, setItems] = useState<string[]>([]);
  return (
    <div className="max-w-md mx-auto overflow-hidden rounded-lg shadow-lg">
      <TodoHeader />
      <TodoEditor setItems={setItems} />
      <TodoList items={items} setItems={setItems} />
    </div>
  );
}
