// pinia/src/components/TodoList.vue
<script setup>
import { useTodoListStore } from "@/stores/todoListStore";
import TodoListItem from "./TodoListItem.vue";

const todoStore = useTodoListStore();
</script>
<template>
  <ul className="divide-y divide-gray-200">
    <template v-if="todoStore.todoList.length > 0">
      <TodoListItem v-for="todo in todoStore.todoList" :todo="todo" />
    </template>
  </ul>
</template>
<style></style>

// 20241203-todo/src/components/TodoList.tsx
import TodoListItem from './TodoListItem';

export default function TodoList({
  todos,
  toggleTodo,
  removeTodo,
}: {
  todos: Todo[];
  toggleTodo: (id: number) => void;
  removeTodo: (id: number) => void;
}) {
  return (
    <ul className='divide-y divide-gray-200'>
      {todos.length > 0 &&
        todos.map((todo) => (
          <TodoListItem
            key={todo.id}
            todo={todo}
            toggleTodo={toggleTodo}
            removeTodo={removeTodo}
          />
        ))}
    </ul>
  );
}
