// 20241202/todoReducer/src/components/TodoList.tsx
import TodoListItem from "./TodoListItem";

export default function TodoList({ todos, handleDelete }: TodoListProps) {
  return (
    <ul className="divide-y divide-gray-200">
      {todos.map((todo, index) => (
        <TodoListItem key={index} todo={todo} handleDelete={handleDelete} />
      ))}
    </ul>
  );
}

// 20250110/todo-pinia/src/components/TodoList.vue
<script setup>
  import { useTodoStore } from '@/stores/todoStore';
  import TodoListItem from './TodoListItem.vue';

  const todoStore = useTodoStore();
</script>
<template>
  <ul className="divide-y divide-gray-200">
    <TodoListItem
      v-for="(todoItem, index) in todoStore.todoList"
      :key="index"
      :index="index"
      :todo="todoItem" />
  </ul>
</template>
<style></style>
