// 20241203/todo_useEffect/src/components/TodoListItem.tsx
import { useId } from "react";

export default function TodoListItem({
  todo,
  removeTodo,
  toggleTodo,
}: {
  todo: Todo;
  removeTodo: (id: number) => void;
  toggleTodo: (id: number) => void;
}) {
  const uuid = useId();

  return (
    <li className="flex items-center justify-between p-3 transition-colors border-b hover:bg-gray-100">
      <div className="flex items-center">
        <input
          id={uuid}
          type="checkbox"
          checked={todo.completed}
          onChange={() => toggleTodo(todo.id)}
          className="w-4 h-4 mr-3 text-blue-500 focus:ring-blue-400"
        />
        <label htmlFor={uuid} className={todo.completed ? "line-through" : ""}>
          {todo.text}
        </label>
      </div>
      <button
        className="ml-4 text-red-500 hover:text-red-700"
        onClick={() => removeTodo(todo.id)}
      >
        Delete
      </button>
    </li>
  );
}

// 20250112/Todo_Props/src/components/TodoListItem.vue
<script>
export default {
  props: {
    todo: Object,
    toggleTodo: Function,
    removeTodo: Function,
  },
};
</script>

<template>
  <li
    className="flex items-center justify-between p-3 border-b hover:bg-gray-100 transition-colors"
  >
    <div className="flex items-center">
      <input
        type="checkbox"
        className="mr-3 h-4 w-4 text-blue-500 focus:ring-blue-400"
        :checked="todo.completed"
        @change="toggleTodo(todo.id)"
      />
      <span :class="{ 'line-through text-gray-500': todo.completed }">
        {{ todo.text }}
      </span>
    </div>
    <button
      @click="removeTodo(todo.id)"
      className="text-red-500 hover:text-red-700 ml-4"
    >
      Delete
    </button>
  </li>
</template>

<style></style>
